spring:
  jpa:
    open-in-view: true
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  datasource:
#    url: db-bongdari.cpijvq4ngvyo.ap-northeast-2.rds.amazonaws.com
    url: jdbc:mysql://db-bongdari.cpijvq4ngvyo.ap-northeast-2.rds.amazonaws.com:3306/jtest?user=admin&password=bongdari
    username: admin
    password: bongdari
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    initialization-mode: always
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: off
      springframework:
        web: info

server:
  error:
    include-message: ALWAYS
    include-stacktrace: never